### ISSUE TITLE
向大佬求救

### ISSUE THREAD

**Issue by liry-code** [EiletXie/cloud2020#1]
大佬帮忙行行好，分享一下seata1.0安装包呗

**Comment by EiletXie** [comment]
好的，已添加到附件了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"LiYu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月27日(星期五) 下午5:26
收件人:&nbsp;"EiletXie/cloud2020"<cloud2020@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[EiletXie/cloud2020] 向大佬求救 (#1)





 
大佬帮忙行行好，分享一下seata1.0安装包呗

**Comment by liry-code** [comment]
> 好的，已添加到附件了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"LiYu"<notifications@github.com&gt;; 发送时间:&nbsp;2020年3月27日(星期五) 下午5:26 收件人:&nbsp;"EiletXie/cloud2020"<cloud2020@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[EiletXie/cloud2020] 向大佬求救 (#1) 大佬帮忙行行好，分享一下seata1.0安装包呗 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
你的附件在哪里，这个仓库没有找到。要不你用百度云盘分享一下？
