### ISSUE TITLE
脑图在哪里，兄弟

### ISSUE THREAD

**Issue by chrisyuqin** [EiletXie/cloud2020#2]
大兄弟，脑图在哪里

**Comment by EiletXie** [comment]
老铁，就在项目中呀，mmap格式的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"chrisYu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月25日(星期六) 晚上10:28
收件人:&nbsp;"EiletXie/cloud2020"<cloud2020@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[EiletXie/cloud2020] 脑图在哪里，兄弟 (#2)





 
大兄弟，脑图在哪里

**Comment by chrisyuqin** [comment]
![image](https://user-images.githubusercontent.com/38065599/80282591-c9b79900-8744-11ea-8bbb-ec4669475efc.png)
mmap 格式的那个文件不能在线打开，也不能下载

**Comment by 929033778** [comment]
这个必须使用“MindManager 2020”才能打开，你去网上找找破解版，我安装试用版将就着用




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"chrisYu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月25日(星期六) 晚上10:34
收件人:&nbsp;"EiletXie/cloud2020"<cloud2020@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [EiletXie/cloud2020] 脑图在哪里，兄弟 (#2)





 

 mmap 格式的那个文件不能在线打开，也不能下载

**Comment by 929033778** [comment]
这个必须使用“MindManager 2020”才能打开，你去网上找找破解版，我安装试用版将就着用




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"chrisYu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月25日(星期六) 晚上10:28
收件人:&nbsp;"EiletXie/cloud2020"<cloud2020@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[EiletXie/cloud2020] 脑图在哪里，兄弟 (#2)





 
大兄弟，脑图在哪里

**Comment by EiletXie** [comment]
，你去了解github如何下载，或者直接下载项目zip包这两种方式，应该可以解决你的问题，下载到本地要对应的 mmap软件才能打开的哈，不过官网可以直接下载并且试用！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "chrisYu"<notifications@github.com&gt;; 
发送时间: 2020年4月25日(星期六) 晚上10:34
收件人: "EiletXie/cloud2020"<cloud2020@noreply.github.com&gt;; 
抄送: "eiletxie"<1215669789@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [EiletXie/cloud2020] 脑图在哪里，兄弟 (#2)





 

 mmap 格式的那个文件不能在线打开，也不能下载

**Comment by EiletXie** [comment]
对的，谢谢帮忙回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ling_dang"<notifications@github.com&gt;; 
发送时间: 2020年4月25日(星期六) 晚上10:37
收件人: "EiletXie/cloud2020"<cloud2020@noreply.github.com&gt;; 
抄送: "eiletxie"<1215669789@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [EiletXie/cloud2020] 脑图在哪里，兄弟 (#2)





 这个必须使用“MindManager 2020”才能打开，你去网上找找破解版，我安装试用版将就着用 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"chrisYu"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年4月25日(星期六) 晚上10:28 
 收件人:&amp;nbsp;"EiletXie/cloud2020"<cloud2020@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"Subscribed"<subscribed@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;[EiletXie/cloud2020] 脑图在哪里，兄弟 (#2) 
 
 
 
 
 
   
 大兄弟，脑图在哪里

**Comment by chrisyuqin** [comment]
big thanks

**Comment by chrisyuqin** [comment]
> 大兄弟，脑图在哪里
